use_frameworks!

platform :ios, '8.0'

target 'HCXXPersonLib_Example' do
  pod 'HCXXPersonLib', :path => '../'

  target 'HCXXPersonLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
